# Generated by Django 3.2 on 2022-01-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(max_length=30)),
                ('chat_password', models.CharField(max_length=30, null=True)),
                ('chat_people', models.IntegerField(default=2)),
                ('chat_flag', models.BooleanField(default=False)),
                ('chat_info', models.CharField(max_length=255)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='member.user')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='ChattingTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'chatting_tag',
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='member.user')),
            ],
            options={
                'db_table': 'chat_user',
            },
        ),
        migrations.CreateModel(
            name='ChatTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('chattingTag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='chat.chattingtag')),
            ],
            options={
                'db_table': 'chat_tag',
            },
        ),
    ]
