
# Generated by Django 3.2 on 2022-01-27 14:54


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adj',
            fields=[
                ('adj_id', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'adj',
            },
        ),
        migrations.CreateModel(
            name='Aivle',
            fields=[
                ('aivle_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'aivle',
            },
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('noun_id', models.AutoField(primary_key=True, serialize=False)),
                ('second', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'noun',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=50, unique=True, verbose_name='사용자이메일')),
                ('user_pw', models.CharField(max_length=255)),
                ('user_nick', models.CharField(max_length=30, unique=True)),
                ('user_track', models.CharField(max_length=10)),
                ('user_class', models.CharField(max_length=10)),
                ('user_profile', models.CharField(max_length=255)),
                ('aivle', models.ForeignKey(db_column='aivle_id', on_delete=django.db.models.deletion.CASCADE, related_name='aivle', to='member.aivle')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
